apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan
  labels:
    app: titan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titan
  template:
    metadata:
      labels:
        app: titan
    spec:
      containers:
        - name: titan
          image: docker.pkg.github.com/zran-nz/nibiru/titan:develop
          restart: always
          ports:
            - containerPort: 80
        imagePullSecrets:
          - name: dockerauth
